# Generated by Django 3.1.3 on 2021-08-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_auto_20210806_0117'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='units',
            field=models.ManyToManyField(to='units.Device'),
        ),
    ]
