# Generated by Django 3.1.3 on 2021-08-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_auto_20210806_0117'),
        ('users', '0002_profile_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='units',
            field=models.ManyToManyField(blank=True, to='units.Device'),
        ),
    ]
