# Generated by Django 3.1.3 on 2021-09-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210812_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alert_module',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='geofence_module',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_module',
            field=models.BooleanField(default=False),
        ),
    ]
