# Generated by Django 3.1.3 on 2021-12-01 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211130_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='view_driver_style_report',
            new_name='view_driving_style_report',
        ),
    ]
