# Generated by Django 3.1.3 on 2021-12-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_view_detailed_report_with_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='view_alert_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_latest_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
