# Generated by Django 3.1.3 on 2021-12-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211206_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='view_group_stop_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_group_trip_report',
            field=models.BooleanField(default=False),
        ),
    ]
