# Generated by Django 3.1.3 on 2021-12-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211207_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='view_geofences',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_group_geofence_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_triggers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_units',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_users',
            field=models.BooleanField(default=False),
        ),
    ]
