# Generated by Django 3.1.3 on 2022-04-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_is_superadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
