# Generated by Django 3.1.3 on 2022-05-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20220408_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='view_day_trip_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_hours_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_temperature_report',
            field=models.BooleanField(default=False),
        ),
    ]
