# Generated by Django 3.1.3 on 2022-05-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20220530_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='view_triggers',
            new_name='view_fleet_triggers',
        ),
        migrations.AddField(
            model_name='profile',
            name='view_mail_lists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_unit_triggers',
            field=models.BooleanField(default=False),
        ),
    ]
