# Generated by Django 3.1.3 on 2022-10-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20220531_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='view_geofences_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_units_group',
            field=models.BooleanField(default=False),
        ),
    ]
