# Generated by Django 3.1.3 on 2021-07-14 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('triggers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetTrigger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('alert_type', models.CharField(choices=[(1001, 'ALERTA DE PANICO'), (1002, 'ALERTA DE DESCONEXION DE BATERIA'), (1003, 'ALERTA DE VELOCIDAD'), (1004, 'ALERTA DE INGRESO A GEOCERCA'), (1005, 'ALERTA DE SALIDA DE GEOCERCA'), (1006, 'ALERTA DE VELOCIDAD POR GEOCERCA')], max_length=200)),
                ('condition', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('send_notification', models.BooleanField(default=True)),
                ('send_mail_notification', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
            ],
            options={
                'unique_together': {('name', 'account')},
            },
        ),
        migrations.DeleteModel(
            name='TriggerA',
        ),
    ]
