# Generated by Django 3.1.3 on 2021-09-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0003_auto_20210818_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleettrigger',
            name='alert_priority',
            field=models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH'), ('V', 'VERY HIGH')], default='L', max_length=9),
        ),
    ]
