# Generated by Django 3.1.3 on 2022-03-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
        ('triggers', '0003_auto_20211217_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleettrigger',
            name='mail_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mails.maillist'),
        ),
    ]
