# Generated by Django 3.1.3 on 2022-03-19 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
        ('triggers', '0006_remove_fleettrigger_mail_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleettrigger',
            name='mail_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mails.maillist'),
        ),
    ]
