# Generated by Django 3.1.3 on 2022-03-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0007_fleettrigger_mail_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleettrigger',
            name='extension1004',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triggers.fleettriggerextension1004'),
        ),
        migrations.AddField(
            model_name='fleettrigger',
            name='extension1005',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triggers.fleettriggerextension1005'),
        ),
    ]
