# Generated by Django 3.1.3 on 2022-03-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0008_auto_20220321_1416'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fleettrigger',
            unique_together=set(),
        ),
    ]
