# Generated by Django 3.1.3 on 2022-03-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_description'),
        ('triggers', '0009_auto_20220321_2151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fleettrigger',
            unique_together={('name', 'account')},
        ),
    ]
