# Generated by Django 3.1.3 on 2022-03-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_description'),
        ('triggers', '0011_auto_20220321_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FleetTriggerExtension1003',
            new_name='Extension1003',
        ),
    ]
