# Generated by Django 3.1.3 on 2022-03-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geofences', '0003_geofence_show_geofence_on_map'),
        ('users', '0018_user_description'),
        ('triggers', '0013_auto_20220326_1236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FleetTriggerExtension1005',
            new_name='Extension1005',
        ),
    ]
