# Generated by Django 3.1.3 on 2022-03-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_description'),
        ('units', '0015_device_osinergmin_process'),
        ('mails', '0005_auto_20220321_1744'),
        ('triggers', '0017_auto_20220326_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleettrigger',
            name='units',
            field=models.ManyToManyField(to='units.Device'),
        ),
        migrations.CreateModel(
            name='UnitTrigger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('alert_type', models.IntegerField(choices=[(1001, 'ALERTA DE PANICO'), (1002, 'ALERTA DE DESCONEXION DE BATERIA'), (1003, 'ALERTA DE VELOCIDAD'), (1004, 'ALERTA DE INGRESO A GEOCERCA'), (1005, 'ALERTA DE SALIDA DE GEOCERCA'), (1006, 'ALERTA DE VELOCIDAD POR GEOCERCA'), (1007, 'ALERTA DE PARADA EN GEOCERCA'), (1008, 'ALERTA DE PARADA FUERA DE GEOCERCA'), (1009, 'ALERTA DE ACELERACION BRUSCA'), (1010, 'ALERTA DE FRENADO BRUSCO'), (1011, 'ALERTA DE GIRO BRUSCO')])),
                ('alert_priority', models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH'), ('V', 'VERY HIGH')], default='L', max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('send_notification', models.BooleanField(default=True)),
                ('send_mail_notification', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('extension1003', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triggers.extension1003')),
                ('extension1004', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triggers.extension1004')),
                ('extension1005', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triggers.extension1005')),
                ('extension1006', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triggers.extension1006')),
                ('extension1007', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triggers.extension1007')),
                ('extension1008', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triggers.extension1008')),
                ('mail_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mails.maillist')),
            ],
        ),
    ]
