# Generated by Django 3.1.3 on 2022-03-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_description'),
        ('triggers', '0018_auto_20220326_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extension1003',
            new_name='FleetTriggerExtension1003',
        ),
        migrations.DeleteModel(
            name='UnitTrigger',
        ),
    ]
