# Generated by Django 3.1.3 on 2022-03-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geofences', '0003_geofence_show_geofence_on_map'),
        ('users', '0018_user_description'),
        ('triggers', '0019_auto_20220328_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extension1004',
            new_name='FleetTriggerExtension1004',
        ),
    ]
