# Generated by Django 3.1.3 on 2022-03-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_description'),
        ('geofences', '0003_geofence_show_geofence_on_map'),
        ('triggers', '0022_auto_20220328_1540'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extension1007',
            new_name='FleetTriggerExtension1007',
        ),
    ]
