# Generated by Django 3.1.3 on 2022-03-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_description'),
        ('triggers', '0025_unittrigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleettrigger',
            name='units',
        ),
        migrations.CreateModel(
            name='UnitTriggerExtension1003',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
            ],
        ),
        migrations.AddField(
            model_name='unittrigger',
            name='extension1003',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triggers.unittriggerextension1003'),
        ),
    ]
