# Generated by Django 3.1.3 on 2022-11-03 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0025_auto_20221011_2209'),
        ('units', '0019_auto_20221027_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('units', models.ManyToManyField(to='units.Device')),
            ],
        ),
    ]
