# Generated by Django 3.1.3 on 2022-11-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forwarders', '0002_remove_queues_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queues',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='queues',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
