# Generated by Django 3.1.3 on 2022-11-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0019_auto_20221027_1756'),
        ('forwarders', '0003_auto_20221103_2308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Queues',
            new_name='Queue',
        ),
    ]
