# Generated by Django 3.1.3 on 2022-11-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forwarders', '0004_auto_20221103_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forwarder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
