# Generated by Django 3.1.3 on 2020-11-22 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uniqueid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=20, unique=True)),
                ('sim_phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('sim_iccid', models.CharField(blank=True, max_length=20, null=True)),
                ('last_timestamp', models.IntegerField(default=0)),
                ('last_latitude', models.FloatField(default=0)),
                ('last_longitude', models.FloatField(default=0)),
                ('last_speed', models.IntegerField(default=-1)),
                ('last_battery_level', models.IntegerField(default=-1)),
                ('last_address', models.CharField(blank=True, default='', max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='units.device')),
            ],
            options={
                'unique_together': {('name', 'account')},
            },
        ),
    ]
