# Generated by Django 3.1.3 on 2021-04-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDigitaOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.PositiveIntegerField()),
                ('output_event', models.CharField(choices=[('MOTOR_LOCK', 'MOTOR_LOCK')], max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.device')),
            ],
            options={
                'unique_together': {('device', 'output', 'output_event')},
            },
        ),
    ]
