# Generated by Django 3.1.3 on 2020-12-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_angle',
            field=models.IntegerField(default=0),
        ),
    ]
