# Generated by Django 3.1.3 on 2021-06-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20210507_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='units',
            field=models.ManyToManyField(to='units.Device'),
        ),
    ]
