# Generated by Django 3.1.3 on 2020-12-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_device_last_angle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_battery_level',
        ),
        migrations.AddField(
            model_name='device',
            name='last_altitude',
            field=models.IntegerField(default=0),
        ),
    ]
