# Generated by Django 3.1.3 on 2020-12-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20201223_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_attributes',
            field=models.TextField(default=''),
        ),
    ]
