# Generated by Django 3.1.3 on 2021-07-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_group_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='sutran_retransmission',
            field=models.BooleanField(default=False),
        ),
    ]
