# Generated by Django 3.1.3 on 2021-05-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_device_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
