# Generated by Django 3.1.3 on 2021-07-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_device_sutran_retransmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_movement',
            field=models.IntegerField(default=0),
        ),
    ]
