# Generated by Django 3.1.3 on 2020-12-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_device_last_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sim_iccid',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='sim_phonenumber',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
