# Generated by Django 3.1.3 on 2021-08-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_device_last_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='show_unit_description_in_map',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='show_unit_name_in_map',
            field=models.BooleanField(default=True),
        ),
    ]
