# Generated by Django 3.1.3 on 2021-01-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_auto_20201228_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='gps_odometer',
            field=models.IntegerField(default=0),
        ),
    ]
