# Generated by Django 3.1.3 on 2021-08-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210812_1556'),
        ('units', '0006_auto_20210806_0117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceDigitaOutput',
            new_name='DeviceDigitalOutput',
        ),
        migrations.CreateModel(
            name='LastAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.IntegerField()),
                ('angle', models.IntegerField()),
                ('address', models.TextField(blank=True, default='')),
                ('alert_type', models.IntegerField()),
                ('alert_description', models.CharField(max_length=400)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.device')),
            ],
        ),
    ]
