# Generated by Django 3.1.3 on 2021-01-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_unit_gps_odometer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='gps_odometer',
        ),
        migrations.AddField(
            model_name='device',
            name='last_gps_odometer',
            field=models.IntegerField(default=0),
        ),
    ]
