# Generated by Django 3.1.3 on 2021-09-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_auto_20210827_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastalert',
            name='alert_priority',
            field=models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH'), ('V', 'VERY HIGH')], default='L', max_length=9),
        ),
    ]
