# Generated by Django 3.1.3 on 2021-01-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_auto_20210126_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_address',
            field=models.TextField(default=''),
        ),
    ]
