# Generated by Django 3.1.3 on 2021-01-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_auto_20210126_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='previous_location',
            field=models.TextField(default=''),
        ),
    ]
