# Generated by Django 3.1.3 on 2021-09-04 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_lastalert_alert_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastalert',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.device', unique=True),
        ),
    ]
