# Generated by Django 3.1.3 on 2021-01-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_device_previous_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_gps_odometer',
            field=models.FloatField(default=0.0),
        ),
    ]
