# Generated by Django 3.1.3 on 2021-09-04 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_auto_20210904_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastalert',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.device'),
        ),
    ]
