# Generated by Django 3.1.3 on 2021-03-15 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0011_deviceinput'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deviceinput',
            unique_together={('device', 'device_type', 'input')},
        ),
    ]
