# Generated by Django 3.1.3 on 2021-03-15 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0012_auto_20210314_1912'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deviceinput',
            unique_together={('device', 'device_type')},
        ),
    ]
