# Generated by Django 3.1.3 on 2021-12-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0012_auto_20211117_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_attributes',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='device',
            name='previous_location',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
