# Generated by Django 3.1.3 on 2022-02-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0013_auto_20211221_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='sutran_retransmission',
            new_name='sutran_process',
        ),
    ]
