# Generated by Django 3.1.3 on 2022-02-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0014_auto_20220204_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='osinergmin_process',
            field=models.BooleanField(default=False),
        ),
    ]
