# Generated by Django 3.1.3 on 2021-03-15 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0014_auto_20210314_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDigitalInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.PositiveIntegerField()),
                ('event', models.CharField(choices=[('IGNITION', 'IGNITION'), ('PANIC', 'PANIC')], max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.device')),
            ],
            options={
                'unique_together': {('device', 'input', 'event')},
            },
        ),
        migrations.DeleteModel(
            name='DeviceInput',
        ),
    ]
