# Generated by Django 3.1.3 on 2022-04-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0015_device_osinergmin_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_hours',
            field=models.IntegerField(default=0),
        ),
    ]
