# Generated by Django 3.1.3 on 2021-03-15 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0015_auto_20210314_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDigitalIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('INPUT', 'INPUT'), ('OUTPUT', 'OUTPUT')], max_length=6)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.device')),
            ],
            options={
                'unique_together': {('device', 'input', 'mode')},
            },
        ),
        migrations.DeleteModel(
            name='DeviceDigitalInput',
        ),
    ]
