# Generated by Django 3.1.3 on 2021-03-15 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0016_auto_20210314_2056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicedigitalio',
            unique_together={('input', 'mode'), ('device', 'input')},
        ),
    ]
