# Generated by Django 3.1.3 on 2021-03-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0018_devicedigitalinput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceDigitalInput',
        ),
    ]
