# Generated by Django 3.1.3 on 2022-11-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forwarders', '0005_auto_20221104_1952'),
        ('units', '0019_auto_20221027_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='forwarders',
            field=models.ManyToManyField(to='forwarders.Forwarder'),
        ),
    ]
