# Generated by Django 3.1.3 on 2021-03-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0020_devicedigitalio_input_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicedigitalio',
            unique_together={('device', 'input', 'input_event')},
        ),
    ]
