# Generated by Django 3.1.3 on 2022-11-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0020_device_forwarders'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='forwarding_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
