# Generated by Django 3.1.3 on 2021-03-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0021_auto_20210317_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedigitalio',
            name='input_event',
            field=models.CharField(choices=[('IGNITION', 'IGNITION'), ('PANIC', 'PANIC')], max_length=50),
        ),
    ]
