# Generated by Django 3.1.3 on 2022-11-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forwarders', '0005_auto_20221104_1952'),
        ('units', '0021_device_forwarding_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='forwarders',
            field=models.ManyToManyField(blank=True, null=True, to='forwarders.Forwarder'),
        ),
    ]
