# Generated by Django 3.1.3 on 2021-03-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0022_auto_20210318_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedigitalio',
            name='mode',
        ),
    ]
