# Generated by Django 3.1.3 on 2022-11-08 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forwarders', '0005_auto_20221104_1952'),
        ('units', '0022_auto_20221107_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='forwarders',
            field=models.ManyToManyField(blank=True, to='forwarders.Forwarder'),
        ),
    ]
