# Generated by Django 3.1.3 on 2021-03-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0023_remove_devicedigitalio_mode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceDigitalIO',
            new_name='DeviceDigitalInput',
        ),
    ]
