# Generated by Django 3.1.3 on 2022-11-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0023_auto_20221108_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
