# Generated by Django 3.1.3 on 2022-11-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0024_device_is_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='imei',
        ),
    ]
