# Generated by Django 3.1.3 on 2022-03-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_auto_20220321_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmailqueue',
            name='it_was_sent',
            field=models.IntegerField(default=0),
        ),
    ]
