# Generated by Django 3.1.3 on 2022-03-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_auto_20220321_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertmailqueue',
            name='alert_name',
        ),
    ]
