# Generated by Django 3.1.3 on 2022-03-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_remove_alertmailqueue_alert_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmailqueue',
            name='alert_latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertmailqueue',
            name='alert_longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
