# Generated by Django 3.1.3 on 2020-11-22 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('geofences', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='geofence',
            unique_together={('name', 'account')},
        ),
    ]
