# Generated by Django 3.1.3 on 2022-04-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geofences', '0003_geofence_show_geofence_on_map'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='geofence',
            unique_together=set(),
        ),
    ]
