# Generated by Django 3.1.3 on 2022-04-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofences', '0004_auto_20220428_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofence',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
