# Generated by Django 3.1.3 on 2022-12-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofences', '0006_geofencegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofence',
            name='enable_speed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geofence',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='geofence',
            name='geojson',
            field=models.TextField(default='{}'),
        ),
    ]
