# Generated by Django 3.1.3 on 2021-07-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unitid', models.IntegerField()),
                ('timestamp', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.IntegerField()),
                ('angle', models.IntegerField()),
                ('alert_type', models.IntegerField()),
                ('alert_description', models.CharField(max_length=400)),
                ('alert_priority', models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH'), ('V', 'VERY HIGH')], default='L', max_length=9)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['unitid', 'timestamp'], name='alerts_aler_unitid_a6b814_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['reference', 'timestamp'], name='alerts_aler_referen_4f6f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['unitid', 'alert_type', 'timestamp'], name='alerts_aler_unitid_cb53ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('alert_type', 'unitid', 'timestamp')},
        ),
    ]
