# Generated by Django 3.1.3 on 2021-05-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddField(
            model_name='alert',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AlterUniqueTogether(
            name='trigger',
            unique_together={('name', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('alert_type', 'unitid', 'timestamp')},
        ),
    ]
