# Generated by Django 3.1.3 on 2021-04-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('alert_type', 'account', 'timestamp')},
        ),
    ]
