# Generated by Django 3.1.3 on 2021-07-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
