# Generated by Django 3.1.3 on 2021-07-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_address'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'timestamp'], name='alerts_aler_alert_t_c095e6_idx'),
        ),
    ]
