# Generated by Django 3.1.3 on 2021-04-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20210413_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='unit_name',
        ),
        migrations.AddField(
            model_name='alert',
            name='unitid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
