# Generated by Django 3.1.3 on 2021-07-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20210714_1436'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alert',
            name='alerts_aler_unitid_a6b814_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='alerts_aler_referen_4f6f2d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together=set(),
        ),
    ]
