# Generated by Django 3.1.3 on 2021-07-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20210714_1444'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('alert_type', 'unitid', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['unitid', 'timestamp'], name='alerts_aler_unitid_a6b814_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['reference', 'timestamp'], name='alerts_aler_referen_4f6f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['unitid', 'alert_type', 'timestamp'], name='alerts_aler_unitid_cb53ac_idx'),
        ),
    ]
