# Generated by Django 3.1.3 on 2021-04-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20210413_2043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('alert_type', 'unitid', 'timestamp')},
        ),
    ]
