# Generated by Django 3.1.3 on 2020-12-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
