# Generated by Django 3.1.3 on 2020-12-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_priority',
            field=models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH'), ('V', 'VERY HIGH')], default='L', max_length=9),
        ),
        migrations.AddField(
            model_name='alert',
            name='angle',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='speed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='unit_name',
            field=models.CharField(default='ATC-234', max_length=50),
            preserve_default=False,
        ),
    ]
