# Generated by Django 3.1.3 on 2020-12-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=50)),
                ('timestamp', models.PositiveIntegerField(default=0)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('angle', models.IntegerField(default=-1)),
                ('speed', models.IntegerField(default=-1)),
                ('satellites', models.PositiveSmallIntegerField(default=-1)),
                ('ignition', models.BooleanField(default=False)),
                ('panic', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
