# Generated by Django 3.1.3 on 2021-05-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
