# Generated by Django 3.1.3 on 2021-06-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SutranLocations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('angle', models.IntegerField(default=-1)),
                ('speed', models.IntegerField(default=-1)),
                ('event', models.CharField(max_length=2)),
                ('device_datetime', models.DateTimeField()),
                ('server_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.BigIntegerField(default=0)),
            ],
        ),
    ]
