# Generated by Django 3.1.3 on 2020-12-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='satellites',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
