# Generated by Django 3.1.3 on 2021-06-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_sutranlocations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SutranLocations',
            new_name='SutranLocation',
        ),
    ]
