# Generated by Django 3.1.3 on 2020-12-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20201210_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='altitude',
            field=models.IntegerField(default=0),
        ),
    ]
