# Generated by Django 3.1.3 on 2021-06-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20210629_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sutranlocation',
            name='server_datetime',
            field=models.DateTimeField(),
        ),
    ]
