# Generated by Django 3.1.3 on 2020-12-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_altitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='ignition',
        ),
        migrations.RemoveField(
            model_name='location',
            name='panic',
        ),
        migrations.RemoveField(
            model_name='location',
            name='satellites',
        ),
        migrations.AddField(
            model_name='location',
            name='attributes',
            field=models.TextField(default=''),
        ),
    ]
