# Generated by Django 3.1.3 on 2022-01-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_osinergminlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='osinergminlocation',
            name='it_was_sent',
            field=models.BooleanField(default=False),
        ),
    ]
