# Generated by Django 3.1.3 on 2022-06-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_sutranpointsofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sutranlocation',
            name='sutran_process',
            field=models.IntegerField(default=0),
        ),
    ]
