# Generated by Django 3.1.3 on 2022-08-31 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_sutranlocation_sutran_process'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('unitid', 'timestamp')},
        ),
    ]
